### ISSUE TITLE
Not Logging In

### ISSUE THREAD

**Issue by gokulapap** [kappithannemo/WhatsAsenaDuplicated#3]
I have given correct asena session , Its not logging in its retrying automatically and it fails continuously

**Comment by kappithannemo** [comment]
will look into it soon.Thanks for mentioning

**Comment by kappithannemo** [comment]
try again. must have fixed it

**Comment by gokulapap** [comment]
Thank you

**Comment by gokulapap** [comment]
again the same error is occuring 

![error](https://user-images.githubusercontent.com/57899332/131951726-97c6cf6f-452c-4e0a-9487-16e7bb6f508d.png)
